phonebook/apps/phone/urls.py
from django.urls import path

from .views import HomePageView, SearchResultsView, CreateView

from phone import views

app_name = 'phone'

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('search/', SearchResultsView.as_view(), name='search_results'),
    path('create_new/', CreateView.as_view(), name='create_new'),
    path('create_new/create/', views.create, name='create'),
    path('edit/<int:id>/', views.edit),
    path('delete/<int:id>/', views.delete),
    path('', views.button_back, name='button_back'),
]

phonebook/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
#from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('phone.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += staticfiles_urlpatterns()

phonebook/apps/phone/models.py
from django.db import models

class Abonent(models.Model):
    id = models.AutoField('ID', auto_created=True, primary_key=True)
    name = models.CharField('Фамилия, Имя, Отчество', max_length=300, blank=True)
    mobile_phone = models.CharField('Сотовый телефон', max_length=100, blank=True)
    gorod_phone = models.CharField('Городской телефон', max_length=100, blank=True)
    internal_phone = models.CharField('Внутренний телефон', max_length=100, blank=True)
    IP_phone = models.CharField('IP телефон', max_length=100, blank=True)
    zvks = models.CharField('E-mail', max_length=100, blank=True)
    pts_phone = models.CharField('Кабинет', max_length=100, blank=True)
    conference_phone = models.CharField('Телефон конференц-связи', max_length=100, blank=True)
    zas_phone = models.CharField('Спутниковый телефон', max_length=100, blank=True)

    class Meta:
        ordering = ["id"]
        verbose_name = 'Абонент'
        verbose_name_plural = 'Абоненты'
    def __str__(self):
        return self.id
    def __str__(self):
        return self.name
    def __str__(self):
        return self.mobile_phone
    def __str__(self):
        return self.gorod_phone
    def __str__(self):
        return self.internal_phone
    def __str__(self):
        return self.IP_phone
    def __str__(self):
        return self.zvks
    def __str__(self):
        return self.pts_phone
    def __str__(self):
        return self.conference_phone
    def __str__(self):
        return self.zas_phone
        
def get_absolute_url(self):
        return reverse("a:detail", kwargs={'a_id': self.a_id})

phonebook/apps/phone/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.http import HttpResponseNotFound
from django.views.generic import ListView
from .models import Abonent
from django.db.models import Q
#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger 

# ...
 
class HomePageView(ListView):
    model = Abonent
    context_object_name = 'abonents'
    template_name = 'home.html'
    def get_queryset(self):
        abonents = Abonent.objects.all()
        return abonents

# поисковая строка
class SearchResultsView(ListView):
    model = Abonent
    template_name = 'search_results.html'

    def get_queryset(self): 
        try:
            query = self.request.GET.get('q')
            #objects_list = Abonent.objects.filter(Q(name__icontains=query))
            objects_list = Abonent.objects.filter(
                Q(name__icontains=query) | Q(mobile_phone__icontains=query) | Q(gorod_phone__icontains=query) | Q(internal_phone__icontains=query) | Q(IP_phone__icontains=query) | Q(zvks__icontains=query) | Q(pts_phone__icontains=query) | Q(conference_phone__icontains=query) | Q(zas_phone__icontains=query)
                )
            return objects_list
        except Abonent.DoesNotExist:
            return HttpResponseNotFound("<h2>Абонент не найден</h2>")

# сохранение данных в бд
class CreateView(ListView):
    model = Abonent
    template_name = 'create_new.html'

def create(request):
    if request.method=="POST":
        objects_list = Abonent()
        objects_list.name = request.POST.get("name")
        objects_list.mobile_phone = request.POST.get("mobile_phone")
        objects_list.gorod_phone = request.POST.get("gorod_phone")
        objects_list.internal_phone = request.POST.get("internal_phone")
        objects_list.IP_phone = request.POST.get("IP_phone")
        objects_list.zvks = request.POST.get("zvks")
        objects_list.pts_phone = request.POST.get("pts_phone")
        objects_list.conference_phone = request.POST.get("conference_phone")
        objects_list.zas_phone = request.POST.get("zas_phone")
        objects_list.save()
        return HttpResponseRedirect("/")
    else:
        return render(request, "create_new.html")


# изменение данных в бд
def edit(request, id):

    try:
        objects_list = Abonent.objects.get(id=id)
        if request.method=="POST":
            objects_list.name = request.POST.get("name")
            objects_list.mobile_phone = request.POST.get("mobile_phone")
            objects_list.gorod_phone = request.POST.get("gorod_phone")
            objects_list.internal_phone = request.POST.get("internal_phone")
            objects_list.IP_phone = request.POST.get("IP_phone")
            objects_list.zvks = request.POST.get("zvks")
            objects_list.pts_phone = request.POST.get("pts_phone")
            objects_list.conference_phone = request.POST.get("conference_phone")
            objects_list.zas_phone = request.POST.get("zas_phone")
            objects_list.save()
            return HttpResponseRedirect("/")
        else:
            return render(request, "edit.html", {"Abonent": Abonent})
    except Abonent.DoesNotExist:
        return HttpResponseNotFound("<h2>Абонент не найден</h2>")
     # button back

def button_back(request):
    return render(request, "home.html", {"Abonent": Abonent})

# удаление данных из бд
def delete(request, id):
    try:
        objects_list = Abonent.objects.get(id=id)
        objects_list.delete()
        return HttpResponseRedirect("/")
    except Abonent.DoesNotExist:
        return HttpResponseNotFound("<h2>Абонент не найден</h2>")

templates/home.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image" href="{% static 'img/icon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" > 
    <script type="text/javascript" language="JavaScript"src="{% static 'js/bootstrap.min.js' %}"></script> 
    <script type="text/javascript" language="JavaScript" src="/static/js/jquery-1.7.2.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Телефонный справочник</title>
  </head>

  <body>
    <header>
        <div class="head">
        <a href="{% url 'phone:home' %}"><img src="/static/img/logo.png" width="50px"></a>
        <a href="{% url 'phone:home' %}"> Телефонный справочник<a/>
        </div>
    </header>

<section class="sticky">
<!------поисковая строка-------->
    

    <form  action="{% url 'phone:search_results' %}" method="get">
        <div class="search">
        <input required="true" name="q" type="text" autofocus class="form-control" placeholder="Введите данные для поиска" value="{{ qwery }}">
        <button type="submit" class="{% url 'phone:search_results' %}">Поиск</button>
        </div>
    </form>


<table class="table_phone2">
    <thead class="table_thead">
        <tr>
        <th class="th1" >Фамилия, Имя, Отчество</th>
        <th class="th2" >Сотовый <br> телефон</th>
        <th class="th3" >Городской <br> телефон</th>
        <th class="th4" >Внутренний <br> телефон</th>
        <th class="th5" >IP телефон</th>
        <th class="th6" >E-mail</th>
        <th class="th7" >Кабинет</th>
        <th class="th8">Телефон <br>конференц-связи</th>
        <th class="th9" >Спутниковый <br> телефон</th>
        </tr>
    </thead>
</table>
</section>

<!------вывод таблицы абонентов--------
<h2>Список абонентов</h2>-->

<table class="table_phone">
    <thead class="table_thead">
        <th class="th1" >Фамилия, Имя, Отчество</th>
        <th class="th2" >Сотовый <br> телефон</th>
        <th class="th3" >Городской <br> телефон</th>
        <th class="th4" >Внутренний <br> телефон</th>
        <th class="th5" >IP телефон</th>
        <th class="th6" >E-mail</th>
        <th class="th7" >Кабинет</th>
        <th class="th8">Телефон <br>конференц-связи</th>
        <th class="th9" >Спутниковый <br> телефон</th>
    </thead>

{% for abonent in object_list %}
        {% if abonent.name == "1. Администрация" %}
        <tr class="header">
        <td  class="red" colspan="9"> {{ abonent.name }} </td>
        </tr>

        {% elif abonent.name == "1.1. Канцелярия" %}
        <tr class="header" style="background-color: rgba(18, 138, 7, 0.1);cursor: pointer">
        <td class="green" colspan="9">{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "1.1.1. Сектор документации" %}
        <tr class="header" style="background-color: rgba(84, 21, 179, 0.1);cursor: pointer;">
        <td  class="purple" colspan="9" >{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "1.1.2. Архив" %}
        <tr class="header" style="background-color: rgba(84, 21, 179, 0.1);cursor: pointer;">
        <td  class="purple" colspan="9" >{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "1.2. Бухгалетрия" %}
        <tr class="header" style="background-color: rgba(18, 138, 7, 0.1);cursor: pointer">
        <td class="green" colspan="9">{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "1.3. Юридический отдел" %}
        <tr class="header" style="background-color: rgba(18, 138, 7, 0.1);cursor: pointer">
        <td class="green" colspan="9">{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "2. Службы логистики и транспорта" %}
        <tr class="header">
        <td  class="red" colspan="9"> {{ abonent.name }} </td>
        </tr>

        {% elif abonent.name == "2.1. Отдел логистики" %}
        <tr class="header" style="background-color: rgba(18, 138, 7, 0.1);cursor: pointer">
        <td class="green" colspan="9">{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "2.1.1. Сектор транспортно-складских операций" %}
        <tr class="header" style="background-color: rgba(84, 21, 179, 0.1);cursor: pointer;">
        <td  class="purple" colspan="9" >{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "2.1.1.1. Склад №1 Сбыта" %}
        <tr class="header" style="background-color: rgba(21, 116, 179, 0.1);cursor: pointer;">
        <td  class="blue" colspan="9" >{{ abonent.name }}</td>
        </tr>

        {% elif abonent.name == "2.1.1.2. Склад №2 Ответственного хранения" %}
        <tr class="header" style="background-color: rgba(21, 116, 179, 0.1);cursor: pointer;">
        <td  class="blue" colspan="9" >{{ abonent.name }}</td>
        </tr>



        {% else %}
    <tr class="hidden">

        <td  class="td1" valign="center" align="center"> {{ abonent.name }} </td>
        <td  class="td2" valign="center" align="center"> {{ abonent.mobile_phone }} </td>
        <td  class="td3" valign="center" align="center"> {{ abonent.gorod_phone }} </td>
        <td  class="td4" valign="center" align="center"> {{ abonent.internal_phone }} </td>
        <td  class="td5" valign="center" align="center"> {{ abonent.IP_phone }} </td>
        <td  class="td6" valign="center" align="center"> {{ abonent.zvks }} </td>
        <td  class="td7" valign="center" align="center"> {{ abonent.pts_phone }} </td>
        <td  class="td8" valign="center" align="center"> {{ abonent.conference_phone }} </td>
        <td  class="td9" valign="center" align="center"> {{ abonent.zas_phone }} </td>
    </tr>
    {% endif %}
{% endfor %}
</table>

<script>

function isHidden(el) {
    var width = el.offsetWidth, height = el.offsetHeight,
    tr = el.nodeName.toLowerCase() === "tr"
    return width === 0 && height === 0 && !tr ?
    true : width > 0 && height > 0 && !tr ? false : getRealDisplay(el)
}



$(this).nextUntil('tr.header')
$(this).toggleClass('expand').nextUntil('tr.header').toggle('fast');
  $('.header').click(function () {
    var $this = $(this);
    $(this).nextUntil('tr.header').toggle('fast').promise().done(function () {
        $this.find('span').text(function (_, value) {
            return value == '-' ? '+' : '-'
        });
    });
});


</script>

</body>
</html>

templates/search_results.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="shortcut icon" type="image" href="{% static 'img/icon.ico' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" > 
    <script type="text/javascript" language="JavaScript"src="{% static 'js/bootstrap.min.js' %}"></script> 
    <script type="text/javascript" language="JavaScript" src="/static/js/jquery-1.7.2.js"></script>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Телефонный справочник ЦО ВНГ РФ</title>
  </head>

  <body>
    <header>
        <div class="head">
        <a href="{% url 'phone:home' %}"><img src="/static/img/logo.png" width="50px"></a>
        <a href="{% url 'phone:home' %}"> Телефонный справочник ЦО ВНГ РФ <a/>
        </div>
    </header>

<section class="sticky">
<!------поисковая строка-------->
    

    <form  action="{% url 'phone:search_results' %}" method="get">
        <div class="search">
        <input required="true" name="q" type="text" autofocus class="form-control" placeholder="Введите данные для поиска" value="{{ qwery }}">
        <button type="submit" class="{% url 'phone:search_results' %}">Поиск</button>
        </div>
    </form>


<table class="table_phone2">
    <thead>
        <th class="th1" >Фамилия, Имя, Отчество</th>
        <th class="th2" >Сотовый телефон</th>
        <th class="th3" >Городской телефон</th>
        <th class="th4" >Внутренний телефон</th>
        <th class="th5" >IP телефон</th>
        <th class="th6" >ЗВКС</th>
        <th class="th7" >Телефон ПТС</th>
        <th class="th8">Телефон <br>конференц-связи</th>
        <th class="th9" >Телефон ЗАС</th>
    </thead>
</table>
</section>



<!------вывод таблицы абонентов--------
<h2>Список абонентов</h2>-->

<table class="table_phone">
    <thead>
        <th class="th1">Фамилия, Имя, Отчество</th>
        <th class="th2">Сотовый телефон</th>
        <th class="th3">Городской телефон</th>
        <th class="th4">Внутренний телефон</th>
        <th class="th5">IP телефон</th>
        <th class="th6">ЗВКС</th>
        <th class="th7">Телефон ПТС</th>
        <th class="th8">Телефон <br>конференц-связи</th>
        <th class="th9">Телефон ЗАС</th>
    </thead>

{% for abonent in object_list %}

    <tr>
        <td  class="td1" valign="center" align="center"> {{ abonent.name }} </td>
        <td  class="td2" valign="center" align="center"> {{ abonent.mobile_phone }} </td>
        <td  class="td3" valign="center" align="center"> {{ abonent.gorod_phone }} </td>
        <td  class="td4" valign="center" align="center"> {{ abonent.internal_phone }} </td>
        <td  class="td5" valign="center" align="center"> {{ abonent.IP_phone }} </td>
        <td  class="td6" valign="center" align="center"> {{ abonent.zvks }} </td>
        <td  class="td7" valign="center" align="center"> {{ abonent.pts_phone }} </td>
        <td  class="td8" valign="center" align="center"> {{ abonent.conference_phone }} </td>
        <td  class="td9" valign="center" align="center"> {{ abonent.zas_phone }} </td>
    </tr>

{% endfor %}
    </table>
</body>
</html>